default: lab3a.c
	gcc -o lab3a lab3a.c
build: lab3a.c
	gcc -o lab3a lab3a.c
clean:
	rm -f super.csv group.csv bitmap.csv inode.csv directory.csv indirect.csv
dist:
	tar -czvf lab3a-004632787.tar.gz lab3a.c README Makefile
